development: 
  cloud_name: "dwsp83m2s"
  api_key: "344256264796797"
  api_secret: "gBVBzVhZ35qyFUX4xDI-s6h2iao"
  secure: true
production:
 cloud_name: "dwsp83m2s"
  api_key: "344256264796797"
  api_secret: "gBVBzVhZ35qyFUX4xDI-s6h2iao"
  enhance_image_tag: true
  static_file_support: true
test:
 cloud_name: "dwsp83m2s"
  api_key: "344256264796797"
  api_secret: "gBVBzVhZ35qyFUX4xDI-s6h2iao"
  enhance_image_tag: true
  static_file_support: false